### ISSUE TITLE
Wallpaper displayed 2 times on the same screen with different resolutions

### ISSUE THREAD

**Issue by Rykian** [epalzeolithe/DisableMonitor-3.0#1]
I've got a weird bug on Disable Monitor.
I have 3 monitors, the MBP16 inches integrated monitor + 2 HD screen. When I disable the integrated monitor, the wallpaper on my main screen have this weird bug:

![Screenshot 2020-01-01 at 11 51 58](https://user-images.githubusercontent.com/154511/71640656-6766f400-2c8e-11ea-8863-bcb348092e34.png)

I've found a workaround, if I switch my main main screen for the other monitor, everything comes in order.

(and thanks for working on this app!)

**Comment by epalzeolithe** [comment]
thx :)

**Comment by jschuur** [comment]
Something similar happened to me in Big Sur ([comment](https://github.com/epalzeolithe/DisableMonitor-3.0/issues/6#issuecomment-765902868)) with v 3.1, which was released just after this issue was closed.
