### ISSUE TITLE
Issues since Big Sur?

### ISSUE THREAD

**Issue by dannyziggy** [epalzeolithe/DisableMonitor-3.0#6]
Wondering if there has been any issues since the update to Big Sur? I've just gotten a new monitor and every time i click disable, i am logged out of my machine and all my apps restart upon login. Currently using a 2019 MBP 13.

Is there anythung I can do to fix this?

**Comment by epalzeolithe** [comment]
Hi 

yes there's a problem with the security policy of Big Sur

i dont know how to work around this

**Comment by welby12** [comment]
Not much of a coder, but I used DisableMonitor up until a week or two ago when I upgraded to Big Sur. I did a little reserach into the issue, and it looks like another app I had used in the past SwitchResX, had this to say on their FAQ in regard to Big Sur

> As far as I know, running BigSur on Intel Macs removed the functionality of disabling a display. This cannot be worked around.
On Apple Silicon Macs, this feature should work correctly (with version 4.11), maybe even better than it ever run on Intel Macs.

**Comment by Atcold** [comment]
So, if I'm reading this correctly, this utility does *not* work (yet) on Big Sur.
Correct?

**Comment by welby12** [comment]
> So, if I'm reading this correctly, this utility does _not_ work (yet) on Big Sur.
> Correct?

In my experience, no it doesn't work. Not even a little bit.

**Comment by jschuur** [comment]
It worked for me just now (Big Sur 11.1). The wallpaper from my second monitor that I disabled moved to my primary one an overlapped with that monitor's wallpaper, but the other monitor went off and I was no longer able to drag windows onto it. it came back when I reenabled it via this app.

One this that was weird was the resolutions it listed in the drop down menu were swapped: For my external monitor it showed the resolutions that my main screen supports and vice versa.

Disabling it also continued to list it under Displays -> Arrangements in System Settings and as a window with its own settings under Displays.

**Comment by epalzeolithe** [comment]
Hi did you modify the code ?

**Comment by jschuur** [comment]
Nope. Just downloaded the latest release (3.1). Two monitors connected via USB-C top HDMI, the laptop is in clamshell mode. If I have a window open on the monitor I disable, its window moves over to the other monitor, so it definitely looks like its off and disabled.

**Comment by epalzeolithe** [comment]
Yes its working now in big sur
there was a bug in first release bug sur

good news
