### ISSUE TITLE
Please add build instructions to README.md

### ISSUE THREAD

**Issue by zsiegel92** [epalzeolithe/DisableMonitor-3.0#9]
Hi there,

I would like to try this out. I want to leave my laptop open for better cooling but don't want to use the internal monitor. If you are able, I'd really appreciate it if you added some build instructions to this repo. Thank you!

**Comment by epalzeolithe** [comment]
Its built, unzip disablemonitor.zip in release section

**Comment by zsiegel92** [comment]
I see. Thanks! If I wanted to build it myself for safety purposes, it would still be great to have instructions. I'm a little wary of just running the `.app`.

**Comment by epalzeolithe** [comment]
Install xcode, have an account on github, and select the button download to xcode, the compile and run :)
